/**
 * Declarative StatefulSet spec for the assistant service group.
 *
 * Defines the static topology of all three containers (assistant, gateway,
 * credential-executor), their volumes, ports, and env vars. Used by both
 * the hatch and upgrade flows to build `docker run` argument arrays.
 */

import { existsSync } from "fs";

import {
  ASSISTANT_INTERNAL_PORT,
  GATEWAY_INTERNAL_PORT,
} from "./environments/paths.js";
import { PROVIDER_ENV_VAR_NAMES } from "../shared/provider-env-vars.js";

const AVATAR_DEVICE_ENV_VAR = "VELLUM_AVATAR_DEVICE";

/** Logical service name used throughout the CLI. */
export type ServiceName = "assistant" | "gateway" | "credential-executor";

/**
 /**
  * The four fields from `dockerResourceNames()` that the builder actually uses.
  * Container/network names come from here; volume names are generated by the
  * `volumeClaimTemplates` in the spec. `ReturnType<typeof dockerResourceNames>`
  * structurally satisfies this interface (it has all these fields plus more).
  */
 export interface DockerResourceNames {
   assistantContainer: string;
   cesContainer: string;
   gatewayContainer: string;
   network: string;
 }

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A static env var whose value is known at spec-definition time. */
interface StaticEnv {
  kind: "static";
  name: string;
  value: string;
}

/**
 * An env var whose value comes from the opts object passed to
 * `buildServiceRunArgs` at container-start time.
 */
interface SecretEnv {
  kind: "secret";
  name: string;
  /** Key in `DockerRunSecrets`. */
  secret: keyof DockerRunSecrets;
}

/**
 * An env var conditionally forwarded from the host process environment.
 * Only emitted when `process.env[hostVar]` is set.
 * Defaults to `name` for `hostVar` when omitted.
 */
interface HostEnv {
  kind: "host";
  name: string;
  hostVar?: string;
}

type EnvEntry = StaticEnv | SecretEnv | HostEnv;

interface VolumeMount {
  /** Logical volume name — maps to a Docker volume via `DockerVolumeClaimTemplate`. */
  volumeName: string;
  mountPath: string;
  readOnly?: boolean;
}

interface PortSpec {
  containerPort: number;
  /**
   * Host-side port. Literal string = use as-is. `"{{ gatewayPort }}"` is
   * a sentinel replaced with the instance-specific gateway port at build time.
   */
  hostPort?: string;
  description?: string;
}

export interface DockerContainerSpec {
  /** K8s-style container name (matches `stateful_template.yaml`). */
  name: string;
  /** Internal CLI `ServiceName` key used by `SERVICE_START_ORDER`. */
  internalName: ServiceName;
  /**
   * Network mode:
   * - "bridge": owns the network (assistant only — gateway port published here).
   * - "container": share the assistant container's network namespace.
   */
  network: "bridge" | "container";
  ports?: PortSpec[];
  env: EnvEntry[];
  volumeMounts: VolumeMount[];
  /**
   * Optional `--user` override for `docker run`. Mirrors K8s
   * `securityContext.runAsUser`. Omitted ⇒ image's `USER` directive wins.
   */
  user?: string;
}

export interface DockerVolumeClaimTemplate {
  name: string;
  dockerVolume: (instanceName: string) => string;
}

export interface DockerStatefulSetSpec {
  containers: DockerContainerSpec[];
  startOrder: ServiceName[];
  volumeClaimTemplates: DockerVolumeClaimTemplate[];
  readiness: {
    endpoint: string;
    timeoutMs: number;
    intervalMs: number;
  };
}

/** Secrets injected at container-start time (from hatch / upgrade opts). */
export interface DockerRunSecrets {
  signingKey?: string;
  bootstrapSecret?: string;
  cesServiceToken?: string;
}

// ---------------------------------------------------------------------------
// Spec
// ---------------------------------------------------------------------------

export const DOCKER_STATEFUL_SET_SPEC: DockerStatefulSetSpec = {
  startOrder: ["assistant", "gateway", "credential-executor"],

  readiness: {
    endpoint: "/readyz",
    timeoutMs: 180_000,
    intervalMs: 1_000,
  },

  volumeClaimTemplates: [
    { name: "assistant-workspace",  dockerVolume: (n) => `${n}-workspace` },
    { name: "ces-bootstrap-socket", dockerVolume: (n) => `${n}-socket` },
    { name: "assistant-ipc-socket", dockerVolume: (n) => `${n}-assistant-ipc` },
    { name: "gateway-ipc-socket",   dockerVolume: (n) => `${n}-gateway-ipc` },
    { name: "gateway-security",     dockerVolume: (n) => `${n}-gateway-sec` },
    { name: "ces-security",         dockerVolume: (n) => `${n}-ces-sec` },
  ],

  containers: [
    {
      name: "assistant-container",
      internalName: "assistant",
      network: "bridge",
      ports: [
        {
          containerPort: GATEWAY_INTERNAL_PORT,
          hostPort: "{{ gatewayPort }}",
          description: "Gateway reverse-proxy (published to host)",
        },
        {
          containerPort: ASSISTANT_INTERNAL_PORT,
          hostPort: `${ASSISTANT_INTERNAL_PORT}`,
          description: "Assistant HTTP API",
        },
      ],
      env: [
        { kind: "static", name: "IS_CONTAINERIZED",         value: "true" },
        { kind: "static", name: "DEBUG_STDOUT_LOGS",         value: "1" },
        { kind: "static", name: "VELLUM_CLOUD",              value: "docker" },
        { kind: "static", name: "RUNTIME_HTTP_HOST",         value: "0.0.0.0" },
        { kind: "static", name: "RUNTIME_HTTP_PORT",         value: `${ASSISTANT_INTERNAL_PORT}` },
        { kind: "static", name: "VELLUM_WORKSPACE_DIR",      value: "/workspace" },
        { kind: "static", name: "VELLUM_BACKUP_DIR",         value: "/workspace/.backups" },
        { kind: "static", name: "VELLUM_BACKUP_KEY_PATH",    value: "/workspace/.backup.key" },
        { kind: "static", name: "CES_CREDENTIAL_URL",        value: "http://localhost:8090" },
        { kind: "static", name: "GATEWAY_IPC_SOCKET_DIR",    value: "/run/gateway-ipc" },
        { kind: "static", name: "ASSISTANT_IPC_SOCKET_DIR",  value: "/run/assistant-ipc" },
        { kind: "secret", name: "CES_SERVICE_TOKEN",         secret: "cesServiceToken" },
        { kind: "secret", name: "ACTOR_TOKEN_SIGNING_KEY",   secret: "signingKey" },
        { kind: "secret", name: "GUARDIAN_BOOTSTRAP_SECRET", secret: "bootstrapSecret" },
        // Provider API keys — forwarded from host if set
        ...Object.values(PROVIDER_ENV_VAR_NAMES).map(
          (v): HostEnv => ({ kind: "host", name: v }),
        ),
        { kind: "host", name: "VELLUM_ENVIRONMENT" },
        { kind: "host", name: "VELLUM_PLATFORM_URL" },
      ],
      volumeMounts: [
        { volumeName: "assistant-workspace",  mountPath: "/workspace" },
        { volumeName: "ces-bootstrap-socket", mountPath: "/run/ces-bootstrap" },
        { volumeName: "assistant-ipc-socket", mountPath: "/run/assistant-ipc" },
        { volumeName: "gateway-ipc-socket",   mountPath: "/run/gateway-ipc" },
      ],
    },

    {
      name: "gateway-sidecar",
      internalName: "gateway",
      network: "container",
      user: "0",
      env: [
        { kind: "static", name: "VELLUM_WORKSPACE_DIR",      value: "/workspace" },
        { kind: "static", name: "GATEWAY_SECURITY_DIR",      value: "/gateway-security" },
        { kind: "static", name: "ASSISTANT_HOST",            value: "localhost" },
        { kind: "static", name: "CES_CREDENTIAL_URL",        value: "http://localhost:8090" },
        { kind: "static", name: "GATEWAY_IPC_SOCKET_DIR",    value: "/run/gateway-ipc" },
        { kind: "static", name: "ASSISTANT_IPC_SOCKET_DIR",  value: "/run/assistant-ipc" },
        { kind: "static", name: "GATEWAY_PORT",              value: `${GATEWAY_INTERNAL_PORT}` },
        { kind: "static", name: "RUNTIME_HTTP_PORT",         value: `${ASSISTANT_INTERNAL_PORT}` },
        { kind: "secret", name: "CES_SERVICE_TOKEN",         secret: "cesServiceToken" },
        { kind: "secret", name: "ACTOR_TOKEN_SIGNING_KEY",   secret: "signingKey" },
        { kind: "secret", name: "GUARDIAN_BOOTSTRAP_SECRET", secret: "bootstrapSecret" },
        { kind: "host",   name: "VELLUM_ENVIRONMENT" },
        { kind: "host",   name: "VELLUM_PLATFORM_URL" },
        { kind: "host",   name: "VELAY_BASE_URL" },
      ],
      volumeMounts: [
        { volumeName: "assistant-workspace",  mountPath: "/workspace" },
        { volumeName: "gateway-security",     mountPath: "/gateway-security" },
        { volumeName: "assistant-ipc-socket", mountPath: "/run/assistant-ipc" },
        { volumeName: "gateway-ipc-socket",   mountPath: "/run/gateway-ipc" },
      ],
    },

    {
      name: "credential-executor-sidecar",
      internalName: "credential-executor",
      network: "container",
      env: [
        { kind: "static", name: "CES_MODE",                  value: "managed" },
        { kind: "static", name: "VELLUM_WORKSPACE_DIR",      value: "/workspace" },
        { kind: "static", name: "CES_BOOTSTRAP_SOCKET_DIR",  value: "/run/ces-bootstrap" },
        { kind: "static", name: "CREDENTIAL_SECURITY_DIR",   value: "/ces-security" },
        { kind: "secret", name: "CES_SERVICE_TOKEN",         secret: "cesServiceToken" },
      ],
      volumeMounts: [
        { volumeName: "assistant-workspace",  mountPath: "/workspace", readOnly: true },
        { volumeName: "ces-bootstrap-socket", mountPath: "/run/ces-bootstrap" },
        { volumeName: "ces-security",         mountPath: "/ces-security" },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export interface BuildServiceRunArgsOpts extends DockerRunSecrets {
  gatewayPort: number;
  imageTags: Record<ServiceName, string>;
  instanceName: string;
  res: DockerResourceNames;
  extraAssistantEnv?: Record<string, string>;
  defaultWorkspaceConfigPath?: string;
  /** Avatar device path, if available. Injected by `docker.ts` after resolving. */
  avatarDevicePath?: string;
}

function resolveVolume(
  spec: DockerStatefulSetSpec,
  instanceName: string,
  volumeName: string,
): string {
  const claim = spec.volumeClaimTemplates.find((v) => v.name === volumeName);
  if (!claim) throw new Error(`docker-statefulset: unknown volume "${volumeName}"`);
  return claim.dockerVolume(instanceName);
}

/**
 * Build `docker run` argument arrays for each container in the StatefulSet.
 * Returns `Record<ServiceName, () => string[]>` — callers evaluate lazily.
 */
export function buildServiceRunArgs(
  opts: BuildServiceRunArgsOpts,
  spec = DOCKER_STATEFUL_SET_SPEC,
): Record<ServiceName, () => string[]> {
  const {
    gatewayPort,
    imageTags,
    instanceName,
    res,
    extraAssistantEnv,
    defaultWorkspaceConfigPath,
    avatarDevicePath,
  } = opts;

  const result = {} as Record<ServiceName, () => string[]>;

  for (const container of spec.containers) {
    const svc = container.internalName;

    result[svc] = () => {
      const args: string[] = ["run", "--init", "-d"];

      // Container name
      const containerName =
        svc === "assistant"
          ? res.assistantContainer
          : svc === "gateway"
            ? res.gatewayContainer
            : res.cesContainer;
      args.push("--name", containerName);

      // User override (mirrors K8s securityContext.runAsUser)
      if (container.user !== undefined) {
        args.push("--user", container.user);
      }

      // Network
      if (container.network === "bridge") {
        args.push(`--network=${res.network}`);
        for (const port of container.ports ?? []) {
          const hostSide =
            port.hostPort === "{{ gatewayPort }}"
              ? `${gatewayPort}`
              : port.hostPort;
          if (hostSide !== undefined) {
            args.push("-p", `${hostSide}:${port.containerPort}`);
          }
        }
      } else {
        args.push(`--network=container:${res.assistantContainer}`);
      }

      // Volume mounts
      for (const mount of container.volumeMounts) {
        const vol = resolveVolume(spec, instanceName, mount.volumeName);
        args.push("-v", mount.readOnly ? `${vol}:${mount.mountPath}:ro` : `${vol}:${mount.mountPath}`);
      }

      // Env vars from spec
      for (const entry of container.env) {
        if (entry.kind === "static") {
          args.push("-e", `${entry.name}=${entry.value}`);
        } else if (entry.kind === "secret") {
          const val = opts[entry.secret];
          if (val) args.push("-e", `${entry.name}=${val}`);
        } else {
          const hostVar = entry.hostVar ?? entry.name;
          const val = process.env[hostVar];
          if (val) args.push("-e", `${entry.name}=${val}`);
        }
      }

      // Assistant-only computed / optional additions
      if (svc === "assistant") {
        args.push(
          "-e", `VELLUM_ASSISTANT_NAME=${instanceName}`,
          "-e", `GATEWAY_INTERNAL_URL=http://localhost:${GATEWAY_INTERNAL_PORT}`,
        );

        if (defaultWorkspaceConfigPath) {
          const cPath = `/tmp/vellum-default-workspace-config-${Date.now()}.json`;
          args.push(
            "-v", `${defaultWorkspaceConfigPath}:${cPath}:ro`,
            "-e", `VELLUM_DEFAULT_WORKSPACE_CONFIG_PATH=${cPath}`,
          );
        }

        if (extraAssistantEnv) {
          for (const [k, v] of Object.entries(extraAssistantEnv)) {
            args.push("-e", `${k}=${v}`);
          }
        }

        if (avatarDevicePath && existsSync(avatarDevicePath)) {
          args.push(
            "--device", `${avatarDevicePath}:${avatarDevicePath}`,
            "-e", `${AVATAR_DEVICE_ENV_VAR}=${avatarDevicePath}`,
          );
        }
      }

      // Image is always last
      args.push(imageTags[svc]);
      return args;
    };
  }

  return result;
}
