import { client } from "@/generated/api/client.gen.js";
import {
  assistantsActivateCreate,
  assistantsBackupsCreate,
  assistantsBackupsRestoreCreate,
  assistantsBackupsRetrieve,
  assistantsHatchCreate,
  assistantsList,
  assistantsRestartDetailCreate,
  assistantsRetireDetailDestroy,
  assistantsRetireDestroy,
  assistantsRetrieve,
} from "@/generated/api/sdk.gen.js";
import type {
  Assistant as GeneratedAssistant,
  HatchAssistantRequest,
} from "@/generated/api/types.gen.js";
import { assertHasResponse, toErrorObject } from "@/lib/api-errors.js";

// DO NOT ADD ONTO THIS FILE. USE THE AUTOGENERATED TANSTACK QUERY HOOKS INSTEAD.
// THIS IS HERE JUST FOR LEGACY COMPATIBILITY.

// This is for unit tests.
const SDK_BASE_OPTIONS =
  typeof window === "undefined"
    ? ({ baseUrl: "http://localhost" } as const)
    : ({} as const);

export type HatchInput = HatchAssistantRequest;
export type Assistant = GeneratedAssistant;

export type HatchResult =
  | { ok: true; status: number; data: Assistant }
  | { ok: false; status: number; error: Record<string, unknown> };

export type GetAssistantResult =
  | { ok: true; status: number; data: Assistant }
  | { ok: false; status: number; error: Record<string, unknown> };

export interface AssistantDiskStatus {
  path: string;
  totalMb: number;
  usedMb: number;
  freeMb: number;
}

export interface AssistantMemoryStatus {
  currentMb: number;
  maxMb: number;
}

export interface AssistantCpuStatus {
  currentPercent: number;
  maxCores: number;
}

export interface AssistantHealthz {
  status: string;
  timestamp: string;
  version?: string;
  disk?: AssistantDiskStatus;
  memory?: AssistantMemoryStatus;
  cpu?: AssistantCpuStatus;
}

export type GetHealthzResult =
  | { ok: true; status: number; data: AssistantHealthz }
  | { ok: false; status: number; error: Record<string, unknown> };

export type DiskPressureState = "disabled" | "ok" | "critical" | "unknown";

export type DiskPressureBlockedCapability =
  | "agent-turns"
  | "background-work"
  | "remote-ingress";

export interface DiskPressureStatus {
  enabled: boolean;
  state: DiskPressureState;
  locked: boolean;
  acknowledged: boolean;
  overrideActive: boolean;
  effectivelyLocked: boolean;
  lockId: string | null;
  usagePercent: number | null;
  thresholdPercent: number;
  path: string | null;
  lastCheckedAt: string | null;
  blockedCapabilities: DiskPressureBlockedCapability[];
  error: string | null;
}

export interface DiskPressureStatusResponse {
  status: DiskPressureStatus;
}

export type GetAssistantDiskPressureStatusResult =
  | { ok: true; status: number; data: DiskPressureStatusResponse }
  | { ok: false; status: number; error: Record<string, unknown> };

export type AcknowledgeAssistantDiskPressureResult =
  | { ok: true; status: number; data: DiskPressureStatusResponse }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function hatchAssistant(
  input?: HatchInput,
): Promise<HatchResult> {
  const { data, error, response } = await assistantsHatchCreate({
    ...SDK_BASE_OPTIONS,
    body: input ?? {},
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to hatch assistant.");

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data as Assistant,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function getAssistant(assistantId?: string): Promise<GetAssistantResult> {
  if (assistantId) {
    const { data, error, response } = await assistantsRetrieve({
      ...SDK_BASE_OPTIONS,
      path: { id: assistantId },
      throwOnError: false,
    });

    assertHasResponse(response, error, "Failed to get assistant.");

    if (response.ok) {
      return {
        ok: true,
        status: response.status,
        data: data as Assistant,
      };
    }

    return {
      ok: false,
      status: response.status,
      error: toErrorObject(error, response),
    };
  }

  // No ID provided — prefer platform-managed assistants, fall back to local.
  // Query platform first to avoid pagination issues with hosting=all.
  const platformResult = await assistantsList({
    ...SDK_BASE_OPTIONS,
    query: { hosting: "platform" },
    throwOnError: false,
  });

  assertHasResponse(platformResult.response, platformResult.error, "Failed to get assistant.");

  if (!platformResult.response.ok) {
    return {
      ok: false,
      status: platformResult.response.status,
      error: toErrorObject(platformResult.error, platformResult.response),
    };
  }

  const platformResults = platformResult.data?.results ?? [];
  if (platformResults.length > 0) {
    return {
      ok: true,
      status: platformResult.response.status,
      data: platformResults[0]!,
    };
  }

  // No platform assistant found — try local.
  const localResult = await assistantsList({
    ...SDK_BASE_OPTIONS,
    query: { hosting: "local" },
    throwOnError: false,
  });

  assertHasResponse(localResult.response, localResult.error, "Failed to get assistant.");

  if (localResult.response.ok) {
    const results = localResult.data?.results ?? [];
    if (results.length > 0) {
      return {
        ok: true,
        status: localResult.response.status,
        data: results[0]!,
      };
    }
  }

  if (!localResult.response.ok) {
    return {
      ok: false,
      status: localResult.response.status,
      error: toErrorObject(localResult.error, localResult.response),
    };
  }

  return {
    ok: false,
    status: 404,
    error: { detail: "No assistants found" },
  };
}

export async function getAssistantHealthz(assistantId: string): Promise<GetHealthzResult> {
  const { data, error, response } = await client.get<
    Record<string, unknown>,
    Record<string, unknown>,
    false
  >({
    ...SDK_BASE_OPTIONS,
    url: `/v1/assistants/{assistant_id}/healthz/`,
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to get assistant healthz.");

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data as unknown as AssistantHealthz,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function getAssistantDiskPressureStatus(
  assistantId: string,
): Promise<GetAssistantDiskPressureStatusResult> {
  const { data, error, response } = await client.get<
    Record<string, unknown>,
    Record<string, unknown>,
    false
  >({
    ...SDK_BASE_OPTIONS,
    url: `/v1/assistants/{assistant_id}/disk-pressure/status/`,
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(
    response,
    error,
    "Failed to get assistant disk pressure status.",
  );

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data as unknown as DiskPressureStatusResponse,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function acknowledgeAssistantDiskPressure(
  assistantId: string,
): Promise<AcknowledgeAssistantDiskPressureResult> {
  const { data, error, response } = await client.post<
    Record<string, unknown>,
    Record<string, unknown>,
    false
  >({
    ...SDK_BASE_OPTIONS,
    url: `/v1/assistants/{assistant_id}/disk-pressure/acknowledge/`,
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(
    response,
    error,
    "Failed to acknowledge assistant disk pressure.",
  );

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data as unknown as DiskPressureStatusResponse,
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export interface AssistantBackup {
  snapshot_name: string;
  pvc: string;
  created_at: string;
  ready_to_use: boolean;
  backup_type: string;
}

export type ListBackupsResult =
  | { ok: true; status: number; data: AssistantBackup[] }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function listAssistantBackups(
  assistantId: string,
): Promise<ListBackupsResult> {
  const { data, error, response } = await assistantsBackupsRetrieve({
    ...SDK_BASE_OPTIONS,
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to list assistant backups.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    if (!Array.isArray(body.backups)) {
      return {
        ok: false,
        status: response.status,
        error: toErrorObject(error ?? body, response),
      };
    }

    return {
      ok: true,
      status: response.status,
      data: body.backups as AssistantBackup[],
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type CreateBackupResult =
  | { ok: true; status: number; data: Record<string, unknown> }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function createAssistantBackup(
  assistantId: string,
): Promise<CreateBackupResult> {
  const { data, error, response } = await assistantsBackupsCreate({
    ...SDK_BASE_OPTIONS,
    path: { assistant_id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to create assistant backup.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    return { ok: true, status: response.status, data: body };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type RestoreBackupResult =
  | { ok: true; status: number; data: Record<string, unknown> }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function restoreAssistantBackup(
  assistantId: string,
  backup: AssistantBackup,
): Promise<RestoreBackupResult> {
  const { data, error, response } = await assistantsBackupsRestoreCreate({
    ...SDK_BASE_OPTIONS,
    path: {
      assistant_id: assistantId,
      snapshot_name: backup.snapshot_name,
    },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to restore assistant backup.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    return { ok: true, status: response.status, data: body };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type RestartResult =
  | { ok: true; data: Record<string, unknown> }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function restartAssistant(assistantId: string): Promise<RestartResult> {
  const { data, error, response } = await assistantsRestartDetailCreate({
    ...SDK_BASE_OPTIONS,
    path: { id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to restart assistant.");

  if (response.ok) {
    const body =
      data && typeof data === "object" && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};

    return { ok: true, data: body };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type RetireResult =
  | { ok: true }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function retireAssistant(): Promise<RetireResult> {
  const { error, response } = await assistantsRetireDestroy({
    ...SDK_BASE_OPTIONS,
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to retire assistant.");

  if (response.ok) {
    return { ok: true };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export async function retireAssistantById(assistantId: string): Promise<RetireResult> {
  const { error, response } = await assistantsRetireDetailDestroy({
    ...SDK_BASE_OPTIONS,
    path: { id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to retire assistant.");

  if (response.ok) {
    return { ok: true };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type ListAssistantsResult =
  | { ok: true; status: number; data: Assistant[] }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function listAssistants(): Promise<ListAssistantsResult> {
  const { data, error, response } = await assistantsList({
    ...SDK_BASE_OPTIONS,
    query: { hosting: "all" },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to list assistants.");

  if (response.ok) {
    return {
      ok: true,
      status: response.status,
      data: data?.results ?? [],
    };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}

export type ActivateResult =
  | { ok: true; data: Assistant }
  | { ok: false; status: number; error: Record<string, unknown> };

export async function activateAssistant(assistantId: string): Promise<ActivateResult> {
  const { data, error, response } = await assistantsActivateCreate({
    ...SDK_BASE_OPTIONS,
    path: { id: assistantId },
    throwOnError: false,
  });

  assertHasResponse(response, error, "Failed to activate assistant.");

  if (response.ok) {
    return { ok: true, data: data as Assistant };
  }

  return {
    ok: false,
    status: response.status,
    error: toErrorObject(error, response),
  };
}
