/**
 * CES approval bridge.
 *
 * Translates a CES `approval_required` response into an interactive
 * confirmation prompt using the existing PermissionPrompter transport.
 * When the guardian approves, the bridge commits the decision back to CES
 * via the `record_grant` RPC rather than through local trust rules.
 *
 * Design principles:
 * - The assistant never sees raw secret values. The rendered proposal text
 *   comes from CES (generated by `@vellumai/service-contracts` rendering).
 * - Approved decisions are persisted inside CES, not in local trust rules.
 * - After approval the bridge returns a `grantId` so the caller can retry
 *   the original tool invocation with the grant attached.
 */

import type {
  ApprovalRequired,
  RecordGrantResponse,
} from "@vellumai/service-contracts/credential-rpc";

import type { PermissionPrompter } from "../permissions/prompter.js";
import type { UserDecision } from "../permissions/types.js";
import { getLogger } from "../util/logger.js";
import type { CesClient } from "./client.js";

const log = getLogger("ces-approval-bridge");

// ---------------------------------------------------------------------------
// Decision mapping
// ---------------------------------------------------------------------------

/**
 * CES approval decisions that the bridge presents to the guardian.
 *
 * Maps the existing confirmation transport decisions to CES grant semantics:
 * - `allow` -> approved (single-use grant, no TTL)
 * - `deny`  -> denied
 */
export interface CesApprovalDecision {
  /** The CES grant decision: approved or denied. */
  grantDecision: "approved" | "denied";
  /** ISO-8601 duration for temporary grants. Undefined for single-use or persistent. */
  ttl: string | undefined;
  /** The type of grant to create (controls persistence behaviour in CES). */
  grantType: "allow_once" | undefined;
  /** The original user decision from the confirmation transport. */
  userDecision: UserDecision;
}

function mapUserDecisionToCesDecision(
  decision: UserDecision,
): CesApprovalDecision {
  switch (decision) {
    case "allow":
      return {
        grantDecision: "approved",
        ttl: undefined,
        grantType: "allow_once",
        userDecision: decision,
      };
    case "deny":
      return {
        grantDecision: "denied",
        ttl: undefined,
        grantType: undefined,
        userDecision: decision,
      };
    default: {
      // Exhaustiveness guard — treat unknown decisions as denials.
      const _exhaustive: never = decision;
      return {
        grantDecision: "denied",
        ttl: undefined,
        grantType: undefined,
        userDecision: decision,
      };
    }
  }
}

// ---------------------------------------------------------------------------
// Bridge result
// ---------------------------------------------------------------------------

export type CesApprovalBridgeResult =
  | {
      outcome: "approved";
      grantId: string;
      userDecision: UserDecision;
    }
  | {
      outcome: "denied";
      userDecision: UserDecision;
    }
  | {
      outcome: "timeout";
    }
  | {
      outcome: "error";
      message: string;
    };

// ---------------------------------------------------------------------------
// Bridge function
// ---------------------------------------------------------------------------

/**
 * Present a CES approval request to the guardian using the existing
 * confirmation prompt infrastructure, then commit the decision to CES
 * via the `record_grant` RPC.
 *
 * @param approval - The `approval_required` payload from CES.
 * @param prompter - The PermissionPrompter that sends confirmation_request
 *   messages to the connected client.
 * @param cesClient - The CES RPC client for committing the grant decision.
 * @param options - Optional configuration for the bridge.
 * @returns The outcome of the approval flow.
 */
export async function bridgeCesApproval(
  approval: ApprovalRequired,
  prompter: PermissionPrompter,
  cesClient: CesClient,
  options?: {
    /** Whether an interactive client is connected. When false, auto-deny. */
    isInteractive?: boolean;
    /** Conversation ID for the confirmation prompt. */
    conversationId?: string;
    /** Abort signal for cooperative cancellation. */
    signal?: AbortSignal;
  },
): Promise<CesApprovalBridgeResult> {
  const { proposal, renderedProposal, proposalHash, sessionId } = approval;

  // Non-interactive sessions have no client to respond — fail closed.
  if (options?.isInteractive === false) {
    log.info(
      {
        event: "ces_approval_bridge_non_interactive",
        proposalHash,
        sessionId,
      },
      "CES approval request denied: non-interactive session",
    );
    return { outcome: "denied", userDecision: "deny" };
  }

  // Build the tool name and input for the confirmation prompt. The tool
  // name uses a `ces:` prefix so the client can distinguish CES approval
  // requests from regular tool confirmation prompts.
  const toolName = `ces:${proposal.type}`;
  const input: Record<string, unknown> = {
    credentialHandle: proposal.credentialHandle,
    purpose: proposal.purpose,
    renderedProposal,
  };

  if (proposal.type === "http") {
    input.method = proposal.method;
    input.url = proposal.url;
  } else if (proposal.type === "command") {
    input.command = proposal.command;
  }

  // Present the confirmation prompt to the guardian. The prompter handles
  // timeouts and abort signals internally.
  const response = await prompter.prompt(
    toolName,
    input,
    "high", // CES approval requests are always high-risk
    [], // No allowlist options — CES manages its own grant patterns
    [], // No scope options — CES manages scope internally
    undefined, // No file diff
    options?.conversationId,
    "host", // CES operations target the host
    false, // Persistent decisions are managed by CES, not trust.json
    options?.signal,
  );

  // Detect prompter timeout: the PermissionPrompter resolves timeouts as
  // decision: "deny" with a decisionContext containing "timed out". Surface
  // this as a distinct outcome so the executor shows a timeout-specific
  // message that encourages retrying rather than implying explicit denial.
  const isTimeout =
    response.decision === "deny" &&
    typeof response.decisionContext === "string" &&
    response.decisionContext.includes("timed out");

  if (isTimeout) {
    log.info(
      {
        event: "ces_approval_bridge_timeout",
        proposalHash,
        sessionId,
      },
      "CES approval bridge: prompter timed out",
    );
    return { outcome: "timeout" };
  }

  const cesDecision = mapUserDecisionToCesDecision(response.decision);

  log.info(
    {
      event: "ces_approval_bridge_decision",
      proposalHash,
      sessionId,
      userDecision: response.decision,
      grantDecision: cesDecision.grantDecision,
      ttl: cesDecision.ttl,
    },
    `CES approval bridge: guardian decision is "${cesDecision.grantDecision}"`,
  );

  return recordCesGrant({
    approval,
    cesClient,
    decision: cesDecision,
    reason: response.decision === "allow" ? "guardian_approved" : "guardian_denied",
  });
}

async function recordCesGrant({
  approval,
  cesClient,
  decision,
  reason,
}: {
  approval: ApprovalRequired;
  cesClient: CesClient;
  decision: CesApprovalDecision;
  reason?: string;
}): Promise<CesApprovalBridgeResult> {
  const { proposal, proposalHash, sessionId, conversationId } = approval;

  if (decision.grantDecision === "denied") {
    return { outcome: "denied", userDecision: decision.userDecision };
  }

  // Commit the approved grant to CES via record_grant RPC.
  try {
    const grantResponse: RecordGrantResponse = await cesClient.call(
      "record_grant",
      {
        decision: {
          proposal,
          proposalHash,
          decision: decision.grantDecision,
          decidedBy: "guardian",
          decidedAt: new Date().toISOString(),
          reason,
          ttl: decision.ttl,
          grantType: decision.grantType,
        },
        sessionId,
        conversationId,
      },
    );

    if (!grantResponse.success) {
      const errorMsg =
        grantResponse.error?.message ?? "Unknown error recording grant";
      log.warn(
        {
          event: "ces_approval_bridge_record_failed",
          proposalHash,
          sessionId,
          error: errorMsg,
        },
        "CES record_grant RPC failed",
      );
      return { outcome: "error", message: errorMsg };
    }

    const grantId = grantResponse.grant?.grantId;
    if (!grantId) {
      log.warn(
        {
          event: "ces_approval_bridge_no_grant_id",
          proposalHash,
          sessionId,
        },
        "CES record_grant succeeded but returned no grantId",
      );
      return {
        outcome: "error",
        message: "Grant recorded but no grantId returned",
      };
    }

    log.info(
      {
        event: "ces_approval_bridge_granted",
        proposalHash,
        sessionId,
        grantId,
        userDecision: decision.userDecision,
      },
      "CES approval bridge: grant recorded successfully",
    );

    return {
      outcome: "approved",
      grantId,
      userDecision: decision.userDecision,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log.warn(
      {
        event: "ces_approval_bridge_rpc_error",
        proposalHash,
        sessionId,
        error: msg,
      },
      "CES record_grant RPC call failed",
    );
    return { outcome: "error", message: msg };
  }
}
