import { AlertCircle, Check, Loader2 } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { Button } from "@vellum/design-library/components/button";
import { Input } from "@vellum/design-library/components/input";
import { toast } from "@vellum/design-library/components/toast";
import { SettingsCard } from "@/domains/settings/components/settings-card.js";
import { useAuthStore } from "@/stores/auth-store.js";
import { looksAutoGenerated } from "@/domains/account/username-heuristics.js";
import {
  checkUsernameAvailable,
  fetchMe,
  updateMe,
  type UpdateMeResult,
  type UserMe,
} from "@/domains/account/profile.js";
import {
  checkAssistantHandleAvailable,
  HANDLE_ERROR_COPY,
  type HandleAvailability,
  type HandleErrorCode,
  updateAssistantHandle,
  type UpdateAssistantHandleResult,
} from "@/domains/account/handle.js";
import type { Assistant } from "@/generated/api/types.gen.js";

// Debounce window before firing the availability check. Tight enough that
// feedback feels live as the user types; loose enough that fast typers
// don't pile up requests.
const AVAILABILITY_DEBOUNCE_MS = 300;
// How long the green "Saved" pill lingers before the button drops back
// to its idle "Save" state.
const SAVED_HOLD_MS = 1400;

type SaveStatus = "idle" | "saving" | "saved" | "error";

// ---------------------------------------------------------------------------
// Shared editor primitive
// ---------------------------------------------------------------------------

/**
 * Discriminated save result the editor expects from the IO layer.
 *
 * Identical shape to ``UpdateMeResult`` / ``UpdateAssistantHandleResult``;
 * extracted as a single type so both sections fan into one editor.
 */
type SaveResult<T> =
  | { kind: "ok"; data: T }
  | { kind: "taken"; message: string }
  | { kind: "invalid"; code: HandleErrorCode | null; message: string }
  | { kind: "error"; message: string };

interface HandleEditorProps<T> {
  /** Current value (empty string when never set). */
  initialHandle: string;
  /** Label rendered above the input. */
  inputLabel: string;
  /**
   * Helper text shown below the input when the field is dirty and there's
   * no error/availability message to display. Doubles as the format hint.
   */
  helperText: string;
  /**
   * Optional helper shown when the field is *unchanged* — i.e. the "idle
   * nudge" copy. Used by the user-handle section to flag auto-generated
   * handles, and by the assistant section to surface "no handle yet".
   */
  idleHelperText?: string;
  /** Live availability probe. Must accept an AbortSignal. */
  checkAvailable(value: string, signal: AbortSignal): Promise<HandleAvailability>;
  /** Save mutation. */
  save(value: string): Promise<SaveResult<T>>;
  /** Called with the server's returned object on a successful save. */
  onSaved(next: T): void;
  /** Toast text shown on a successful save. */
  saveSuccessToast: string;
  /**
   * Stable test/DOM identifier prefix so two editors on the same card
   * don't share ARIA ids or input names.
   */
  fieldId: string;
}

/**
 * Single-input handle editor.
 *
 * Renders an ``@``-prefixed input, debounced availability probe, animated
 * inline state pip, live preview, and a Save button. All IO is injected so
 * the same shell drives both the user-handle and assistant-handle surfaces.
 *
 * The probe is allowed to fail — when it does we surface a transient
 * message and still allow Save. The mutation endpoint does the
 * authoritative validation server-side.
 */
function HandleEditor<T>({
  initialHandle,
  inputLabel,
  helperText,
  idleHelperText,
  checkAvailable,
  save,
  onSaved,
  saveSuccessToast,
  fieldId,
}: HandleEditorProps<T>) {
  const [value, setValue] = useState(initialHandle);
  const [availability, setAvailability] = useState<HandleAvailability | null>(
    null,
  );
  const [isChecking, setIsChecking] = useState(false);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>("idle");
  const [serverError, setServerError] = useState<string | null>(null);
  const prefersReducedMotion = useReducedMotion();

  // Track the in-flight availability request so a fast follow-up keystroke
  // can cancel it before the response lands.
  const inflightRef = useRef<AbortController | null>(null);

  const normalized = useMemo(() => value.trim().toLowerCase(), [value]);
  const isUnchanged = normalized === initialHandle.toLowerCase();

  // ----------------------------------------------------------------
  // Debounced availability check
  // ----------------------------------------------------------------
  useEffect(() => {
    if (isUnchanged || normalized.length === 0) {
      setIsChecking(false);
      inflightRef.current?.abort();
      return;
    }

    const controller = new AbortController();
    inflightRef.current?.abort();
    inflightRef.current = controller;
    setIsChecking(true);

    const timer = window.setTimeout(async () => {
      try {
        const result = await checkAvailable(normalized, controller.signal);
        if (!controller.signal.aborted) {
          setAvailability(result);
        }
      } catch (err) {
        if (!controller.signal.aborted) {
          setServerError(
            err instanceof Error
              ? err.message
              : "Couldn't check availability.",
          );
        }
      } finally {
        if (!controller.signal.aborted) {
          setIsChecking(false);
        }
      }
    }, AVAILABILITY_DEBOUNCE_MS);

    return () => {
      window.clearTimeout(timer);
      controller.abort();
    };
  }, [normalized, isUnchanged, checkAvailable]);

  // ----------------------------------------------------------------
  // Derived UI state
  // ----------------------------------------------------------------
  const errorText: string | null = (() => {
    if (serverError) return serverError;
    if (availability && !availability.available) {
      // Prefer the server's message; fall back to local copy keyed by code.
      const code = availability.code as HandleErrorCode | null;
      return (
        availability.message ??
        (code ? HANDLE_ERROR_COPY[code] : "Please choose a different handle.")
      );
    }
    return null;
  })();

  const helperOrIdle: string | null = (() => {
    if (errorText) return null;
    if (isUnchanged) return idleHelperText ?? null;
    if (isChecking) return "Checking availability…";
    if (availability?.available) return "Available.";
    return null;
  })();

  // Save is gated on the probe NOT having returned an explicit "taken /
  // invalid" — but a probe failure (network blip, rate limit, 5xx) must NOT
  // lock the user out. In that case `availability` stays null, we show the
  // transient error inline, and the mutation endpoint does the authoritative
  // validation server-side.
  const isSaveable =
    !isUnchanged &&
    !isChecking &&
    availability?.available !== false &&
    saveStatus !== "saving";

  const handleSave = useCallback(async () => {
    if (!isSaveable) return;
    setSaveStatus("saving");
    setServerError(null);

    const result = await save(normalized);
    if (result.kind === "ok") {
      setSaveStatus("saved");
      onSaved(result.data);
      toast.success(saveSuccessToast);
      // Drop back to idle after the success pill has had its moment.
      window.setTimeout(() => setSaveStatus("idle"), SAVED_HOLD_MS);
      return;
    }
    if (result.kind === "taken") {
      setSaveStatus("idle");
      setAvailability({
        available: false,
        code: "taken",
        message: result.message,
      });
      return;
    }
    if (result.kind === "invalid") {
      setSaveStatus("idle");
      setAvailability({
        available: false,
        code: result.code,
        message: result.message,
      });
      return;
    }
    setSaveStatus("error");
    setServerError(result.message);
    toast.error(result.message);
  }, [isSaveable, normalized, onSaved, save, saveSuccessToast]);

  // ----------------------------------------------------------------
  // Right-side affordance: animated state pip
  // ----------------------------------------------------------------
  const rightIcon = (() => {
    if (isUnchanged && value.length > 0) return null;
    if (value.length === 0) return null;
    const motionKey = isChecking
      ? "checking"
      : availability?.available
        ? "available"
        : availability?.available === false
          ? "invalid"
          : null;
    if (!motionKey) return null;
    return (
      <AnimatePresence mode="wait" initial={false}>
        <motion.span
          key={motionKey}
          initial={prefersReducedMotion ? false : { opacity: 0, scale: 0.85 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={prefersReducedMotion ? undefined : { opacity: 0, scale: 0.85 }}
          transition={{ duration: 0.14, ease: "easeOut" }}
          className="flex items-center"
          aria-hidden={motionKey !== "available" && motionKey !== "invalid"}
        >
          {motionKey === "checking" && (
            <Loader2 className="h-4 w-4 animate-spin text-[var(--content-tertiary)]" />
          )}
          {motionKey === "available" && (
            <Check
              className="h-4 w-4 text-[var(--system-positive-strong)]"
              aria-label="Available"
            />
          )}
          {motionKey === "invalid" && (
            <AlertCircle
              className="h-4 w-4 text-[var(--system-negative-strong)]"
              aria-label="Not available"
            />
          )}
        </motion.span>
      </AnimatePresence>
    );
  })();

  // ----------------------------------------------------------------
  // Live preview — the moment of meaning. Shows what your handle
  // renders as everywhere else (roadmap comments, mentions, etc.).
  // When there's no current handle and nothing typed yet, fall back
  // to a neutral placeholder so the preview line still anchors the
  // empty state.
  // ----------------------------------------------------------------
  const previewHandle =
    normalized.length > 0
      ? normalized
      : initialHandle.length > 0
        ? initialHandle
        : "—";
  const previewIsDirty = !isUnchanged && normalized.length > 0;

  // ----------------------------------------------------------------
  // Button label — empty save button is a dead pixel, so let it
  // narrate its own state instead.
  // ----------------------------------------------------------------
  const saveLabel = (() => {
    switch (saveStatus) {
      case "saving":
        return (
          <span className="inline-flex items-center gap-1.5">
            <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden />
            Saving…
          </span>
        );
      case "saved":
        return (
          <span className="inline-flex items-center gap-1.5">
            <Check className="h-3.5 w-3.5" aria-hidden />
            Saved
          </span>
        );
      default:
        return "Save";
    }
  })();

  return (
    <div className="flex flex-col gap-4">
      <Input
        label={inputLabel}
        value={value}
        onChange={(e) => {
          // Strip whitespace as the user types — pasted values often
          // bring leading/trailing whitespace, and the server lowercases
          // anyway, so do it here for clean preview.
          setValue(e.target.value.replace(/\s+/g, ""));
          setAvailability(null);
          setServerError(null);
        }}
        autoCorrect="off"
        autoCapitalize="none"
        spellCheck={false}
        maxLength={30}
        leftIcon={
          <span
            className="select-none font-mono text-[var(--content-tertiary)]"
            aria-hidden
          >
            @
          </span>
        }
        rightIcon={rightIcon}
        errorText={errorText ?? undefined}
        helperText={helperOrIdle ?? helperText}
        aria-invalid={Boolean(errorText)}
        fullWidth
        data-testid={`${fieldId}-input`}
      />

      {/* Live preview — quiet supporting line, not a callout box. */}
      <div
        className="flex items-baseline gap-2 text-label-small-default text-[var(--content-tertiary)]"
        aria-live="polite"
      >
        <span>Appears as</span>
        <AnimatePresence mode="popLayout" initial={false}>
          <motion.span
            key={previewHandle}
            initial={prefersReducedMotion ? false : { opacity: 0, y: 1 }}
            animate={{ opacity: 1, y: 0 }}
            exit={prefersReducedMotion ? undefined : { opacity: 0, y: -1 }}
            transition={{ duration: 0.14, ease: "easeOut" }}
            className={
              "font-mono " +
              (previewIsDirty
                ? "text-[var(--content-primary)]"
                : "text-[var(--content-secondary)]")
            }
          >
            @{previewHandle}
          </motion.span>
        </AnimatePresence>
      </div>

      <div className="flex justify-end">
        <Button
          variant="primary"
          size="compact"
          onClick={handleSave}
          disabled={!isSaveable}
          aria-live="polite"
          data-testid={`${fieldId}-save`}
        >
          {saveLabel}
        </Button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// User handle section
// ---------------------------------------------------------------------------

interface UserHandleSectionProps {
  initial: UserMe;
  onSaved: (next: UserMe) => void;
}

function UserHandleSection({ initial, onSaved }: UserHandleSectionProps) {
  const refreshSession = useAuthStore.use.refreshSession();

  // Legacy handles derived from email local-parts at WorkOS signup ("user42",
  // etc.) get a friendlier nudge — surfaces the editor's purpose to users
  // who never picked their handle.
  const idleHelperText = looksAutoGenerated(initial.username)
    ? "Your handle was auto-generated at signup — pick one you like."
    : undefined;

  const save = useCallback(
    async (value: string): Promise<SaveResult<UserMe>> => {
      const result: UpdateMeResult = await updateMe({ username: value });
      // ``UpdateMeResult`` is structurally identical to ``SaveResult<UserMe>``
      // except it types ``code`` as ``UsernameErrorCode`` while ``SaveResult``
      // accepts the alias ``HandleErrorCode``. They're the same union, so the
      // cast is purely a type-system bridge.
      return result as SaveResult<UserMe>;
    },
    [],
  );

  const checkAvailable = useCallback(
    (v: string, signal: AbortSignal): Promise<HandleAvailability> => {
      // The user-handle availability shape is the same as the assistant
      // shape (same codes, same message field) so we can return it
      // verbatim — the cast just satisfies the TS contract.
      return checkUsernameAvailable(v, signal) as Promise<HandleAvailability>;
    },
    [],
  );

  const handleSaved = useCallback(
    (next: UserMe) => {
      onSaved(next);
      // Refresh the auth-store session so the cached ``username`` reflects
      // the new handle everywhere it's read (header avatar dropdown, etc.).
      void refreshSession();
    },
    [onSaved, refreshSession],
  );

  return (
    <HandleEditor<UserMe>
      initialHandle={initial.username}
      inputLabel="Handle"
      helperText="Lowercase letters, digits, hyphens, and underscores. 3–30 characters."
      idleHelperText={idleHelperText}
      checkAvailable={checkAvailable}
      save={save}
      onSaved={handleSaved}
      saveSuccessToast="Profile updated."
      fieldId="user-handle"
    />
  );
}

// ---------------------------------------------------------------------------
// Assistant handle section
// ---------------------------------------------------------------------------

interface AssistantHandleSectionProps {
  assistant: Assistant;
  onSaved: (next: Assistant) => void;
}

function AssistantHandleSection({
  assistant,
  onSaved,
}: AssistantHandleSectionProps) {
  // Assistants may not have a handle yet (the column is nullable; auto-derivation
  // only kicks in on rename when the assistant has a non-default name). Treat
  // ``null`` as an empty string for the editor so the "pick one" flow works.
  const currentHandle = assistant.handle ?? "";

  const idleHelperText =
    currentHandle.length === 0
      ? "Your assistant doesn't have a handle yet — claim one to make it mentionable."
      : undefined;

  const save = useCallback(
    async (value: string): Promise<SaveResult<Assistant>> => {
      const result: UpdateAssistantHandleResult = await updateAssistantHandle(
        assistant.id,
        value,
      );
      return result;
    },
    [assistant.id],
  );

  const checkAvailable = useCallback(
    (v: string, signal: AbortSignal): Promise<HandleAvailability> => {
      return checkAssistantHandleAvailable(assistant.id, v, signal);
    },
    [assistant.id],
  );

  return (
    <HandleEditor<Assistant>
      initialHandle={currentHandle}
      inputLabel="Assistant handle"
      helperText="Lowercase letters, digits, hyphens, and underscores. 3–30 characters."
      idleHelperText={idleHelperText}
      checkAvailable={checkAvailable}
      save={save}
      onSaved={onSaved}
      saveSuccessToast="Assistant handle updated."
      fieldId="assistant-handle"
    />
  );
}

// ---------------------------------------------------------------------------
// Loading skeleton
// ---------------------------------------------------------------------------

/**
 * Loading skeleton — mirrors the resolved layout so there is no
 * content-shift when fetchMe() returns. Uses the design-system pulse
 * pattern; no inline animation styles.
 */
function ProfileCardSkeleton() {
  return (
    <div className="flex flex-col gap-4" aria-busy aria-live="polite">
      <div className="flex flex-col gap-2">
        <div className="h-3 w-16 animate-pulse rounded bg-[var(--surface-muted)]" />
        <div className="h-9 w-full animate-pulse rounded-md bg-[var(--surface-muted)]" />
        <div className="h-3 w-72 animate-pulse rounded bg-[var(--surface-muted)]" />
      </div>
      <div className="h-9 w-full animate-pulse rounded-md bg-[var(--surface-muted)]" />
      <div className="flex items-center justify-between gap-3">
        <div className="h-3 w-60 animate-pulse rounded bg-[var(--surface-muted)]" />
        <div className="h-7 w-16 animate-pulse rounded-md bg-[var(--surface-muted)]" />
      </div>
      <span className="sr-only">Loading your profile…</span>
    </div>
  );
}

// ---------------------------------------------------------------------------
// ProfileCard — the public component
// ---------------------------------------------------------------------------

interface ProfileCardProps {
  /**
   * Platform assistant whose handle this user can edit. ``null`` /
   * ``undefined`` hides the assistant section entirely (self-hosted-local
   * fallback, no platform assistant, or feature gated off upstream).
   */
  assistant?: Assistant | null;
}

/**
 * Settings card for editing handles on the user's Vellum identity surface.
 *
 * Renders two independently-saveable sections:
 *
 *   1. **User handle** — always visible; fetches ``/v1/user/me/`` on mount.
 *      The auth-store ``username`` lags a session refresh behind a save,
 *      so we re-read from the server for the editor's initial value.
 *   2. **Assistant handle** — only when an ``assistant`` prop is supplied
 *      (a non-local platform assistant). Lets the user claim a public
 *      handle for the assistant or replace the auto-derived one.
 *
 * Each section has its own Save button; mistakes in one don't block the
 * other.
 */
export function ProfileCard({
  assistant: initialAssistant,
}: ProfileCardProps = {}) {
  const [me, setMe] = useState<UserMe | null>(null);
  const [error, setError] = useState<string | null>(null);
  const prefersReducedMotion = useReducedMotion();

  // Mirror the assistant prop into local state so a successful save can
  // replace the cached snapshot without a full re-fetch from the parent.
  const [assistant, setAssistant] = useState<Assistant | null>(
    initialAssistant ?? null,
  );

  // Keep local state in sync when the parent's prop changes (e.g. a
  // refetch fired by ``useAssistantWithHealthz``). We only honor the
  // parent's value when our local snapshot hasn't been edited past it —
  // a fresh prop always wins because the parent owns identity here.
  useEffect(() => {
    setAssistant(initialAssistant ?? null);
  }, [initialAssistant]);

  useEffect(() => {
    let cancelled = false;
    void fetchMe()
      .then((data) => {
        if (!cancelled) setMe(data);
      })
      .catch((err) => {
        if (!cancelled) {
          setError(
            err instanceof Error ? err.message : "Failed to load profile.",
          );
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <SettingsCard title="Profile" subtitle="Your public handle on Vellum.">
      {error ? (
        <p className="text-body-small-default text-[var(--system-negative-strong)]">
          {error}
        </p>
      ) : me ? (
        <motion.div
          initial={prefersReducedMotion ? false : { opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.22, ease: "easeOut" }}
          className="flex flex-col gap-6"
        >
          <UserHandleSection initial={me} onSaved={setMe} />
          {assistant && (
            <>
              {/* Inline divider — keeps the two sections visually grouped
                  inside a single card while letting them act independently.
                  Two-tone border to match the SettingsCard surface. */}
              <div className="border-t border-[var(--border-subtle)]" />
              <AssistantHandleSection
                assistant={assistant}
                onSaved={setAssistant}
              />
            </>
          )}
        </motion.div>
      ) : (
        <ProfileCardSkeleton />
      )}
    </SettingsCard>
  );
}
